# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-13 04:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Singers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
                ('bio', models.CharField(max_length=500)),
                ('img', models.ImageField(upload_to='singerpics')),
            ],
        ),
    ]
