# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-14 23:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='singers',
            name='img',
            field=models.ImageField(upload_to='singerpics/'),
        ),
    ]
